/*
 * Copyright (c) 2023 Akitsugu Komiyama
 * under the MIT License
 */



// OPENAIのAPIのKEYの設定 
SET_OPENAI_KEY:

    $OPENAI_KEY = getenv("OPENAI_KEY");

    if ($OPENAI_KEY == "") {
        $OPENAI_KEY = ""; // 直接ここでAPIのKEYの文字列を指定しても良いですが、あまり推奨はしません。直書きする場合、このマクロを迂闊に配布して他者にAPIのキーが漏れないよう注意。
    }


BLAZOR_SERVER_SETTING:

    // Blazorサーバーの実行ファイル(BlazorApp.exeなど) へのフルパスを指定。
    $BLAZOR_FULLPATH = @"G:\repogitory\gen_blazor_openai_chatgpt\src\bin\Release\net6.0\publish\BlazorApp.exe";

    #TARGET_BROWSER_PANE = 1; // 個別ブラウザ枠:2  共用ブラウザ枠:1    大きな事情がない限りはChatGPT/OpenAIの使用用途と考えると共通枠の方が良い。

    #BLAZOR_HOSTPORT = 49901;



CREATE_BLAZOR_SERVER_UNIQUE_PORT:


    $COMMAND_LINE = sprintf("""" "%s" "%s" "%d" call_by_hidemaru %s"""", $BLAZOR_FULLPATH, $OPENAI_KEY, #BLAZOR_HOSTPORT, hidemarudir + "\\hidemaru.exe");
    runex $COMMAND_LINE
        , 0     //sync   0:async, 1:sync
        , 0, "" //stdin  0:none, 1:auto, 2:<file, 3:(reserved),
                //       4:current content, 5:selection
        , 0, "" //stdout 0:none, 1:auto, 2:>file 3:>>file, 4:new window,
                //       5:insert, 6:replace, 7:>output pane, 8:>>output pane
        , 0, "" //stderr 0:none, 1:auto or >>stdout, 2-8:same as stdout's param
        , 4, "" //folder 0:none, 1:current, 2:specify 3:(reserved), 4:exe's
        , 2     //show   0:auto, 1:show, 2:hide, 3-13:ShellExecute()'s SW_*
        , 0     //draw   0:draw, 1:no draw when stdout redirected
        , 0     //encode 0:ansi, 2:utf-16, 6:utf-8
        , 0     //extended flags
    ;


SHOW_BROWSER_PANE_BY_HTTP_URL:
    sleep 500; // ブレイザーは立ち上がり中にアクセスしたらレイアウト崩れる
    // ブラウザ枠で表示
    showbrowserpane 1, #TARGET_BROWSER_PANE;
    // 対応するポートでPHPサーバーが立っているので、そのURLをブラウザ枠に表示。
    $BLAZOR_URL = sprintf("http://localhost:%d/chat", #BLAZOR_HOSTPORT);
    setbrowserpaneurl $BLAZOR_URL, #TARGET_BROWSER_PANE;
